### ISSUE TITLE
Copy to Clipboard doesn't work in slideout

### ISSUE THREAD

**Issue by DowleyDeveloped** [john-henry/matrix-block-anchor#3]
Firstly, lovely plugin!

I've found the copy to clipboard doesn't work in slideout, but does work when you have the matrix block inline.

**Comment by john-henry** [comment]
Thanks Charlie. Ill look into it this week.

**Comment by john-henry** [comment]
Hi @DowleyDeveloped This should now be fixed in https://github.com/john-henry/matrix-block-anchor/releases/tag/2.0.1 or https://github.com/john-henry/matrix-block-anchor/releases/tag/1.0.2 depending on your version of Craft
